<a href="https://colab.research.google.com/github/venkatasai-eng/MLA0305-REINFORCEMENT-LEARNING-/blob/main/EXP_NO_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

np.random.seed(42)

states = 5
actions = 2
episodes = 100
gamma = 0.9

def environment(state, action):
    if action == 1:
        next_state = min(state + 1, states - 1)
    else:
        next_state = max(state - 1, 0)

    reward = 10 if next_state == states - 1 else -1
    return next_state, reward

transition_count = np.zeros((states, actions, states))
reward_sum = np.zeros((states, actions))

for episode in range(episodes):

    state = 0

    for _ in range(10):

        action = np.random.randint(actions)

        next_state, reward = environment(
            state, action
        )

        transition_count[
            state, action, next_state
        ] += 1

        reward_sum[state, action] += reward

        state = next_state

        if state == states - 1:
            break

transition_model = np.zeros_like(transition_count)
reward_model = np.zeros_like(reward_sum)

for s in range(states):
    for a in range(actions):

        total = np.sum(
            transition_count[s, a]
        )

        if total > 0:
            transition_model[s, a] = (
                transition_count[s, a] / total
            )
            reward_model[s, a] = (
                reward_sum[s, a] / total
            )

V = np.zeros(states)

for _ in range(100):

    new_V = np.zeros(states)

    for s in range(states - 1):

        values = []

        for a in range(actions):

            value = reward_model[s, a]

            value += gamma * np.sum(
                transition_model[s, a] * V
            )

            values.append(value)

        new_V[s] = max(values)

    V = new_V

policy = np.zeros(states, dtype=int)

for s in range(states - 1):

    values = []

    for a in range(actions):

        value = reward_model[s, a]

        value += gamma * np.sum(
            transition_model[s, a] * V
        )

        values.append(value)

    policy[s] = np.argmax(values)

print("Learned Environment Model:")
print(np.round(transition_model, 2))

print("\nLearned Value Function:")
print(np.round(V, 2))

print("\nOptimal Policy:")

for s in range(states):

    if s == states - 1:
        print("State", s, ": Goal")
    else:
        print(
            "State", s, ":",
            "Left" if policy[s] == 0 else "Right"
        )

print("\nModel-Based Reinforcement Learning Completed.")

Learned Environment Model:
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]]

 [[1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]

 [[0. 1. 0. 0. 0.]
  [0. 0. 0. 1. 0.]]

 [[0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]

Learned Value Function:
[ 4.58  6.2   8.   10.    0.  ]

Optimal Policy:
State 0 : Right
State 1 : Right
State 2 : Right
State 3 : Right
State 4 : Goal

Model-Based Reinforcement Learning Completed.
